import { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Minimalist Wool Coat",
    price: 299,
    category: "Outerwear",
    image: "https://images.unsplash.com/photo-1539533113208-f6df818d5438?auto=format&fit=crop&q=80&w=800",
    description: "A timeless minimalist wool coat crafted from premium Italian wool. Features a clean silhouette and hidden button closure.",
    isNew: true,
  },
  {
    id: "2",
    name: "Silk Slip Dress",
    price: 159,
    category: "Dresses",
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&q=80&w=800",
    description: "Elegant silk slip dress with adjustable spaghetti straps. Perfect for evening wear or layering.",
    isSale: true,
    salePrice: 129,
  },
  {
    id: "3",
    name: "Cashmere Turtleneck",
    price: 189,
    category: "Knitwear",
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&q=80&w=800",
    description: "Ultra-soft cashmere turtleneck sweater. A winter essential that combines warmth with sophistication.",
  },
  {
    id: "4",
    name: "Tailored Linen Trousers",
    price: 120,
    category: "Trousers",
    image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&q=80&w=800",
    description: "High-waisted tailored trousers made from breathable linen. Ideal for warm weather elegance.",
  },
  {
    id: "5",
    name: "Structured Leather Tote",
    price: 450,
    category: "Accessories",
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&q=80&w=800",
    description: "Handcrafted structured leather tote with spacious interior. Features gold-tone hardware and reinforced handles.",
    isNew: true,
  },
  {
    id: "6",
    name: "Oversized Cotton Shirt",
    price: 89,
    category: "Shirts",
    image: "https://images.unsplash.com/photo-1598033129183-c4f50c7176c8?auto=format&fit=crop&q=80&w=800",
    description: "Classic oversized button-down shirt in crisp organic cotton. A versatile piece for any wardrobe.",
  },
  {
    id: "7",
    name: "Suede Chelsea Boots",
    price: 210,
    category: "Footwear",
    image: "https://images.unsplash.com/photo-1638247025967-b4e38f787b76?auto=format&fit=crop&q=80&w=800",
    description: "Premium suede Chelsea boots with elasticated side panels and pull tabs. Durable rubber sole for all-day comfort.",
  },
  {
    id: "8",
    name: "Gold Link Necklace",
    price: 75,
    category: "Jewelry",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800",
    description: "18k gold-plated link necklace. A bold statement piece that adds a touch of luxury to any outfit.",
    isSale: true,
    salePrice: 55,
  },
];
