import { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Minimalist Wool Coat",
    price: 299,
    category: "WOMEN",
    image: "https://images.unsplash.com/photo-1539533113208-f6df818d5438?auto=format&fit=crop&q=80&w=800",
    description: "A timeless minimalist wool coat crafted from premium Italian wool. Features a clean silhouette and hidden button closure.",
    isNew: true,
  },
  {
    id: "2",
    name: "Silk Slip Dress",
    price: 159,
    category: "WOMEN",
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&q=80&w=800",
    description: "Elegant silk slip dress with adjustable spaghetti straps. Perfect for evening wear or layering.",
    isSale: true,
    salePrice: 129,
  },
  {
    id: "3",
    name: "Tailored Wool Suit",
    price: 589,
    category: "MEN",
    image: "https://images.unsplash.com/photo-1594932224010-75f2a77d5250?auto=format&fit=crop&q=80&w=800",
    description: "A sharp, modern tailored suit in fine charcoal wool. Perfect for formal occasions and professional settings.",
  },
  {
    id: "4",
    name: "L'Essence de Nuit",
    price: 120,
    category: "FRAGNANCES",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=800",
    description: "A sophisticated evening fragrance with notes of sandalwood, amber, and rare night-blooming jasmine.",
  },
  {
    id: "5",
    name: "Velvet Matte Lipstick",
    price: 45,
    category: "MAKEUP",
    image: "https://images.unsplash.com/photo-1586776977607-310e9c725c37?auto=format&fit=crop&q=80&w=800",
    description: "Long-wearing velvet matte lipstick in our signature 'Atelier Red'. Infused with hydrating oils for comfort.",
    isNew: true,
  },
  {
    id: "6",
    name: "Structured Leather Tote",
    price: 450,
    category: "LEATHER GOODS",
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&q=80&w=800",
    description: "Handcrafted structured leather tote with spacious interior. Features gold-tone hardware and reinforced handles.",
  },
  {
    id: "7",
    name: "Gold Link Necklace",
    price: 210,
    category: "JEWELRY",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800",
    description: "18k gold-plated link necklace. A bold statement piece that adds a touch of luxury to any outfit.",
    isSale: true,
    salePrice: 175,
  },
  {
    id: "8",
    name: "Chronograph Heritage",
    price: 1250,
    category: "WATCHES",
    image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&q=80&w=800",
    description: "A masterpiece of horology. Features a Swiss movement, sapphire crystal, and genuine alligator strap.",
    isNew: true,
  },
  {
    id: "9",
    name: "Bespoke Evening Gown",
    price: 4500,
    category: "SURPRISES TE GIFTS",
    image: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&q=80&w=800",
    description: "A one-of-a-kind evening gown tailored to your exact measurements. Hand-embroidered with silk threads and crystals.",
  },
];
